<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block "\Openpay\Stores\Block\Checkout\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if (isset($_SESSION['pdf_url'])): ?>
            <div style="width: 70%">
                <h2 style="font-weight:600;">Localiza tu tienda más cercana dando click
                    <a target="_blank" href="https://www.paynet.com.mx/mapa-tiendas/index.html" style="font-weight:600;">aqui</a>
                </h2>                
                <iframe id="pdf" src="<?php echo $_SESSION["pdf_url"] ?>" style="width:100%; height:950px;" frameborder="0"></iframe>    
            </div>  
        <?php endif; ?>  
    <?php endif; ?>
</div>
